# Generated by Django 4.2.2 on 2023-06-23 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqttapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnee',
            name='capteur',
            field=models.ForeignKey(db_column='capteur_id', on_delete=django.db.models.deletion.CASCADE, to='mqttapp.capteur'),
        ),
    ]
