# Generated by Django 4.2.1 on 2023-06-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('piece', models.CharField(max_length=255)),
                ('emplacement', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('capteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.capteur')),
            ],
        ),
    ]
