# Generated by Django 4.2.1 on 2023-06-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capteur',
            name='emplacement',
        ),
    ]
